
version: "3"
volumes:
  db-store:

x-dev-base: &dev-base
  build: .
  environment:
    DATABASE_URL: mysql://docker:docker@mysql:3306/nest_next_sample
    SERVER_APOLLO_URI: http://api:3300
    PUBLIC_APOLLO_URI: http://localhost:3300
    TZ: Asia/Tokyo
  volumes:
    - .:/app
    - /app/node_modules
    - /app/packages/web/node_modules

services:

  frontend:
    << : *dev-base
    working_dir: /app/packages/web
    tty: true
    depends_on:
      - backend
    ports:
      - "3000:3000"