packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.29.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  wrangler:  ^3.107.3
  "@cloudflare/workers-types": ^4.20250620.0
  hono: ^4.7.9