packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.19.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  wrangler:  ^3.103.2
  "@cloudflare/workers-types": ^4.20250109.0
  hono: ^4.6.20