packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.5.4
  wrangler:  ^3.107.3
  "@cloudflare/workers-types": ^4.20250129.0
  hono: ^4.6.20