packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.9.1
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  wrangler:  ^3.57.2
  "@cloudflare/workers-types": ^4.20240821.1
  hono: ^4.5.9