packages:
  - apps/*
  - tooling/*

catalog:
  eslint: ^9.9.1
  prettier: ^3.3.3
  tailwindcss: ^3.4.10
  typescript: ^5.5.4
  wrangler:  ^3.107.3
  "@cloudflare/workers-types": ^4.20250129.0
  hono: ^4.6.20